mail:
  # simple config
  host: 127.0.0.1
  port: 110
  from: 000@test.com

  # list config
  default-recipients:
    - 111@test.com
    - 222@test.com

  # map config
  additional-headers:
    header1: one
    header2: two

  # class member config
  credentials:
    name: kobe
    password: passwd

  # map class config
  member-credentials:
    kobe:
      name: kb
      password: passwd
    james:
      name: lj
      password: passwd



